/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsLayoutRouteImport } from './routes/projects/_layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as ProjectsLayoutIndexRouteImport } from './routes/projects/_layout/index'
import { Route as ProjectProjectIdSidebarRouteImport } from './routes/project/$projectId/_sidebar'
import { Route as ProjectProjectIdNosidebarRouteImport } from './routes/project/$projectId/_nosidebar'
import { Route as AuthLayoutRegisterRouteImport } from './routes/auth/_layout/register'
import { Route as AuthLayoutLoginRouteImport } from './routes/auth/_layout/login'
import { Route as ProjectProjectIdSidebarIndexRouteImport } from './routes/project/$projectId/_sidebar/index'
import { Route as ProjectProjectIdNosidebarSecurityRouteImport } from './routes/project/$projectId/_nosidebar/security'
import { Route as ProjectProjectIdNosidebarMonitoringRouteImport } from './routes/project/$projectId/_nosidebar/monitoring'
import { Route as ProjectProjectIdNosidebarMembersRouteImport } from './routes/project/$projectId/_nosidebar/members'
import { Route as ProjectProjectIdNosidebarDeploymentsRouteImport } from './routes/project/$projectId/_nosidebar/deployments'
import { Route as ProjectProjectIdNosidebarDatabaseRouteImport } from './routes/project/$projectId/_nosidebar/database'
import { Route as ProjectProjectIdNosidebarBranchesRouteImport } from './routes/project/$projectId/_nosidebar/branches'

const ProjectsRouteImport = createFileRoute('/projects')()
const AuthRouteImport = createFileRoute('/auth')()
const ProjectProjectIdRouteImport = createFileRoute('/project/$projectId')()

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLayoutRoute = ProjectsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProjectsRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const ProjectsLayoutIndexRoute = ProjectsLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsLayoutRoute,
} as any)
const ProjectProjectIdSidebarRoute = ProjectProjectIdSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdNosidebarRoute =
  ProjectProjectIdNosidebarRouteImport.update({
    id: '/_nosidebar',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const ProjectProjectIdSidebarIndexRoute =
  ProjectProjectIdSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectIdSidebarRoute,
  } as any)
const ProjectProjectIdNosidebarSecurityRoute =
  ProjectProjectIdNosidebarSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)
const ProjectProjectIdNosidebarMonitoringRoute =
  ProjectProjectIdNosidebarMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)
const ProjectProjectIdNosidebarMembersRoute =
  ProjectProjectIdNosidebarMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)
const ProjectProjectIdNosidebarDeploymentsRoute =
  ProjectProjectIdNosidebarDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)
const ProjectProjectIdNosidebarDatabaseRoute =
  ProjectProjectIdNosidebarDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)
const ProjectProjectIdNosidebarBranchesRoute =
  ProjectProjectIdNosidebarBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => ProjectProjectIdNosidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/projects': typeof ProjectsLayoutRouteWithChildren
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/project/$projectId': typeof ProjectProjectIdSidebarRouteWithChildren
  '/projects/': typeof ProjectsLayoutIndexRoute
  '/project/$projectId/branches': typeof ProjectProjectIdNosidebarBranchesRoute
  '/project/$projectId/database': typeof ProjectProjectIdNosidebarDatabaseRoute
  '/project/$projectId/deployments': typeof ProjectProjectIdNosidebarDeploymentsRoute
  '/project/$projectId/members': typeof ProjectProjectIdNosidebarMembersRoute
  '/project/$projectId/monitoring': typeof ProjectProjectIdNosidebarMonitoringRoute
  '/project/$projectId/security': typeof ProjectProjectIdNosidebarSecurityRoute
  '/project/$projectId/': typeof ProjectProjectIdSidebarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/projects': typeof ProjectsLayoutIndexRoute
  '/auth/login': typeof AuthLayoutLoginRoute
  '/auth/register': typeof AuthLayoutRegisterRoute
  '/project/$projectId': typeof ProjectProjectIdSidebarIndexRoute
  '/project/$projectId/branches': typeof ProjectProjectIdNosidebarBranchesRoute
  '/project/$projectId/database': typeof ProjectProjectIdNosidebarDatabaseRoute
  '/project/$projectId/deployments': typeof ProjectProjectIdNosidebarDeploymentsRoute
  '/project/$projectId/members': typeof ProjectProjectIdNosidebarMembersRoute
  '/project/$projectId/monitoring': typeof ProjectProjectIdNosidebarMonitoringRoute
  '/project/$projectId/security': typeof ProjectProjectIdNosidebarSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/_layout': typeof ProjectsLayoutRouteWithChildren
  '/auth/_layout/login': typeof AuthLayoutLoginRoute
  '/auth/_layout/register': typeof AuthLayoutRegisterRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/_nosidebar': typeof ProjectProjectIdNosidebarRouteWithChildren
  '/project/$projectId/_sidebar': typeof ProjectProjectIdSidebarRouteWithChildren
  '/projects/_layout/': typeof ProjectsLayoutIndexRoute
  '/project/$projectId/_nosidebar/branches': typeof ProjectProjectIdNosidebarBranchesRoute
  '/project/$projectId/_nosidebar/database': typeof ProjectProjectIdNosidebarDatabaseRoute
  '/project/$projectId/_nosidebar/deployments': typeof ProjectProjectIdNosidebarDeploymentsRoute
  '/project/$projectId/_nosidebar/members': typeof ProjectProjectIdNosidebarMembersRoute
  '/project/$projectId/_nosidebar/monitoring': typeof ProjectProjectIdNosidebarMonitoringRoute
  '/project/$projectId/_nosidebar/security': typeof ProjectProjectIdNosidebarSecurityRoute
  '/project/$projectId/_sidebar/': typeof ProjectProjectIdSidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/auth/login'
    | '/auth/register'
    | '/project/$projectId'
    | '/projects/'
    | '/project/$projectId/branches'
    | '/project/$projectId/database'
    | '/project/$projectId/deployments'
    | '/project/$projectId/members'
    | '/project/$projectId/monitoring'
    | '/project/$projectId/security'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projects'
    | '/auth/login'
    | '/auth/register'
    | '/project/$projectId'
    | '/project/$projectId/branches'
    | '/project/$projectId/database'
    | '/project/$projectId/deployments'
    | '/project/$projectId/members'
    | '/project/$projectId/monitoring'
    | '/project/$projectId/security'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/_layout'
    | '/projects'
    | '/projects/_layout'
    | '/auth/_layout/login'
    | '/auth/_layout/register'
    | '/project/$projectId'
    | '/project/$projectId/_nosidebar'
    | '/project/$projectId/_sidebar'
    | '/projects/_layout/'
    | '/project/$projectId/_nosidebar/branches'
    | '/project/$projectId/_nosidebar/database'
    | '/project/$projectId/_nosidebar/deployments'
    | '/project/$projectId/_nosidebar/members'
    | '/project/$projectId/_nosidebar/monitoring'
    | '/project/$projectId/_nosidebar/security'
    | '/project/$projectId/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/_layout': {
      id: '/projects/_layout'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLayoutRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/projects/_layout/': {
      id: '/projects/_layout/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsLayoutIndexRouteImport
      parentRoute: typeof ProjectsLayoutRoute
    }
    '/project/$projectId/_sidebar': {
      id: '/project/$projectId/_sidebar'
      path: ''
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdSidebarRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/_nosidebar': {
      id: '/project/$projectId/_nosidebar'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdNosidebarRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/auth/_layout/register': {
      id: '/auth/_layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/project/$projectId/_sidebar/': {
      id: '/project/$projectId/_sidebar/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdSidebarIndexRouteImport
      parentRoute: typeof ProjectProjectIdSidebarRoute
    }
    '/project/$projectId/_nosidebar/security': {
      id: '/project/$projectId/_nosidebar/security'
      path: '/security'
      fullPath: '/project/$projectId/security'
      preLoaderRoute: typeof ProjectProjectIdNosidebarSecurityRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
    '/project/$projectId/_nosidebar/monitoring': {
      id: '/project/$projectId/_nosidebar/monitoring'
      path: '/monitoring'
      fullPath: '/project/$projectId/monitoring'
      preLoaderRoute: typeof ProjectProjectIdNosidebarMonitoringRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
    '/project/$projectId/_nosidebar/members': {
      id: '/project/$projectId/_nosidebar/members'
      path: '/members'
      fullPath: '/project/$projectId/members'
      preLoaderRoute: typeof ProjectProjectIdNosidebarMembersRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
    '/project/$projectId/_nosidebar/deployments': {
      id: '/project/$projectId/_nosidebar/deployments'
      path: '/deployments'
      fullPath: '/project/$projectId/deployments'
      preLoaderRoute: typeof ProjectProjectIdNosidebarDeploymentsRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
    '/project/$projectId/_nosidebar/database': {
      id: '/project/$projectId/_nosidebar/database'
      path: '/database'
      fullPath: '/project/$projectId/database'
      preLoaderRoute: typeof ProjectProjectIdNosidebarDatabaseRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
    '/project/$projectId/_nosidebar/branches': {
      id: '/project/$projectId/_nosidebar/branches'
      path: '/branches'
      fullPath: '/project/$projectId/branches'
      preLoaderRoute: typeof ProjectProjectIdNosidebarBranchesRouteImport
      parentRoute: typeof ProjectProjectIdNosidebarRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProjectsLayoutRouteChildren {
  ProjectsLayoutIndexRoute: typeof ProjectsLayoutIndexRoute
}

const ProjectsLayoutRouteChildren: ProjectsLayoutRouteChildren = {
  ProjectsLayoutIndexRoute: ProjectsLayoutIndexRoute,
}

const ProjectsLayoutRouteWithChildren = ProjectsLayoutRoute._addFileChildren(
  ProjectsLayoutRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsLayoutRoute: typeof ProjectsLayoutRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsLayoutRoute: ProjectsLayoutRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ProjectProjectIdNosidebarRouteChildren {
  ProjectProjectIdNosidebarBranchesRoute: typeof ProjectProjectIdNosidebarBranchesRoute
  ProjectProjectIdNosidebarDatabaseRoute: typeof ProjectProjectIdNosidebarDatabaseRoute
  ProjectProjectIdNosidebarDeploymentsRoute: typeof ProjectProjectIdNosidebarDeploymentsRoute
  ProjectProjectIdNosidebarMembersRoute: typeof ProjectProjectIdNosidebarMembersRoute
  ProjectProjectIdNosidebarMonitoringRoute: typeof ProjectProjectIdNosidebarMonitoringRoute
  ProjectProjectIdNosidebarSecurityRoute: typeof ProjectProjectIdNosidebarSecurityRoute
}

const ProjectProjectIdNosidebarRouteChildren: ProjectProjectIdNosidebarRouteChildren =
  {
    ProjectProjectIdNosidebarBranchesRoute:
      ProjectProjectIdNosidebarBranchesRoute,
    ProjectProjectIdNosidebarDatabaseRoute:
      ProjectProjectIdNosidebarDatabaseRoute,
    ProjectProjectIdNosidebarDeploymentsRoute:
      ProjectProjectIdNosidebarDeploymentsRoute,
    ProjectProjectIdNosidebarMembersRoute:
      ProjectProjectIdNosidebarMembersRoute,
    ProjectProjectIdNosidebarMonitoringRoute:
      ProjectProjectIdNosidebarMonitoringRoute,
    ProjectProjectIdNosidebarSecurityRoute:
      ProjectProjectIdNosidebarSecurityRoute,
  }

const ProjectProjectIdNosidebarRouteWithChildren =
  ProjectProjectIdNosidebarRoute._addFileChildren(
    ProjectProjectIdNosidebarRouteChildren,
  )

interface ProjectProjectIdSidebarRouteChildren {
  ProjectProjectIdSidebarIndexRoute: typeof ProjectProjectIdSidebarIndexRoute
}

const ProjectProjectIdSidebarRouteChildren: ProjectProjectIdSidebarRouteChildren =
  {
    ProjectProjectIdSidebarIndexRoute: ProjectProjectIdSidebarIndexRoute,
  }

const ProjectProjectIdSidebarRouteWithChildren =
  ProjectProjectIdSidebarRoute._addFileChildren(
    ProjectProjectIdSidebarRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdNosidebarRoute: typeof ProjectProjectIdNosidebarRouteWithChildren
  ProjectProjectIdSidebarRoute: typeof ProjectProjectIdSidebarRouteWithChildren
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdNosidebarRoute: ProjectProjectIdNosidebarRouteWithChildren,
  ProjectProjectIdSidebarRoute: ProjectProjectIdSidebarRouteWithChildren,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
