compressionLevel: mixed

enableGlobalCache: false

# nodeLinker: pnp
nodeLinker: node-modules

# yarnPath: .yarn/releases/yarn-4.1.0.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - current
    - darwin
    - win32

